#!/bin/bash

ARGS="--param ../Labs/rmi-2223/sensors-config.xml"
ARGS+=" --lab ../Labs/rmi-2223/sensors-lab.xml"
ARGS+=" --grid ../Labs/rmi-2223/sensors-grid.xml"
ARGS+=" --scoring 1"
(cd simulator; ./simulator $ARGS) &

sleep 1

(cd Viewer; ./Viewer --autoconnect)

killall simulator

echo Bye
